services:
  mariadb:
    image: mariadb:10.11
    container_name: sakila-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: sakila
      MARIADB_USER: marc
      MARIADB_PASSWORD: marc
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql

  mysql:
    image: mysql:8
    container_name: sakila-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: marc
      MYSQL_PASSWORD: marc
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: sakila-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgresql:
    image: postgres:15
    container_name: sakila-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server /data --console-address ":9001"
