#!/bin/bash

SWD="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

(
  cd "${SWD}"

  source .env
  : "${GITHUB_PACKAGES_TOKEN:?Need to set GITHUB_PACKAGES_TOKEN in .env}"

  GITHUB_PACKAGES_TOKEN="$GITHUB_PACKAGES_TOKEN" \
    envsubst < "${SWD}/.m2/settings.xml.template" > "${SWD}/.m2/settings.xml"

  ./mvnw -s "${SWD}/.m2/settings.xml" "$@"
) || exit 1
