spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: sakila-rest
  config:
    import:
      - optional:classpath:db-${DB_SYSTEM}.yml
      - dotenv:.env

# === SWAGGER CONFIGURATION ===
springdoc:
  swagger-ui:
    path: /docs

# === BUGSNAG CONFIGURATION ===
bugsnag:
  key: ${BUGSNAG_API_KEY}

# === S3 CONFIGURATION ===
s3:
  bucket: ${S3_BUCKET}
  region: ${S3_REGION}
  access-key: ${S3_ACCESS_KEY_ID}
  secret-key: ${S3_SECRET_ACCESS_KEY}
  url: ${S3_URL}
