# === SERVER CONFIGURATION ===
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  # === SECURITY CONFIGURATION ===
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.issuer}

  # === DATABASE CONFIGURATION ===
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration/mariadb
    baseline-on-migrate: true

  # === JACKSON (JSON) CONFIGURATION ===
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  # === CACHING ===
  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}
      username: ${DATA_REDIS_USERNAME}
      password: ${DATA_REDIS_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
      use-key-prefix: true

# === AUTH0 CONFIGURATION ===
auth0:
  domain: ${AUTH0_DOMAIN}
  issuer: ${AUTH0_ISSUER}
  audience: ${AUTH0_AUDIENCE}
  mgmt-client-id: ${AUTH0_MGMT_CLIENT_ID}
  mgmt-client-secret: ${AUTH0_MGMT_CLIENT_SECRET}
  app-client-id: ${AUTH0_APP_CLIENT_ID}
  app-client-secret: ${AUTH0_APP_CLIENT_SECRET}
  connection: Username-Password-Authentication
