spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: sakila-rest
  config:
    import:
      - optional:classpath:db-${DB_SYSTEM}.yml
      - dotenv:.env

# === SWAGGER CONFIGURATION ===
springdoc:
  swagger-ui:
    path: /docs

# === BUGSNAG CONFIGURATION ===
bugsnag:
  key: ${BUGSNAG_API_KEY}
