ALTER TABLE film ADD COLUMN uuid BINARY(16);
ALTER TABLE `store` ADD COLUMN uuid BINARY(16);
ALTER TABLE customer ADD COLUMN uuid BINARY(16);

UPDATE film SET uuid = UUID_TO_BIN(UUID(), 1) WHERE uuid IS NULL;
ALTER TABLE film MODIFY COLUMN uuid BINARY(16) NOT NULL;
ALTER TABLE film ADD CONSTRAINT film_uuid_unique UNIQUE (uuid);

UPDATE `store` SET uuid = UUID_TO_BIN(UUID(), 1) WHERE uuid IS NULL;
ALTER TABLE `store` MODIFY COLUMN uuid BINARY(16) NOT NULL;
ALTER TABLE `store` ADD CONSTRAINT store_uuid_unique UNIQUE (uuid);

UPDATE customer SET uuid = UUID_TO_BIN(UUID(), 1) WHERE uuid IS NULL;
ALTER TABLE customer MODIFY COLUMN uuid BINARY(16) NOT NULL;
ALTER TABLE customer ADD CONSTRAINT customer_uuid_unique UNIQUE (uuid);