name: Build and Deploy to Railway

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository checkout including LFS support
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # 2. Java + Maven Setup
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Maven Build
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # 4. Railway CLI Setup
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # 5. Railway Deployment
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT_KEY }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE_KEY }}
        run: |
          railway up
