name: Multi-OS Release with Maven Build

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: prod
    strategy:
      matrix:
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"  # oder 21
          distribution: "temurin"
          architecture: "x64"

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests

      - name: Prepare release artifact
        run: |
          mkdir -p release-artifacts
          cp target/*.jar release-artifacts/sakila-rest-${{ matrix.os }}.jar
          ls -l release-artifacts

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: sakila-rest-${{ matrix.os }}
          path: release-artifacts/*.jar

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag version
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          generate_release_notes: true
          files: release-artifacts/**/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
